---
- name: Install Mysql 5.6.20
  hosts: 
    - 10.0.2.12
    - 10.0.2.13
  remote_user: yan
  sudo: yes
  vars:
    mysql_basedir: /opt/mysql
    mysql_datadir: /opt/mysql5.6.20/data
    port: 3306
  pre_tasks:
    - name: Install Libaio 
      yum: name=libaio state=present

  tasks:
    - name: Create User & Group For MySQL
      user: name=mysql 
            home=/opt/mysql
            createhome=no 
            shell=/bin/false
      tags: "deploy"

    - name: Copy MySQL Binary Tarball
      copy: src=/home/yan/software/mysql-5.6.20-linux-glibc2.5-x86_64.tar.gz
            dest=/opt
      tags: "deploy"

    - name: Untar Tarball
      command: /bin/tar xzvf mysql-5.6.20-linux-glibc2.5-x86_64.tar.gz
               chdir=/opt
               creates=/opt/mysql-5.6.20-linux-glibc2.5-x86_64
      tags: "deploy"

    - name: Change Owner
      file: path=/opt/mysql-5.6.20-linux-glibc2.5-x86_64
            owner=mysql
            group=mysql
            recurse=yes

    - name: Create Link to mysql
      file: src=/opt/mysql-5.6.20-linux-glibc2.5-x86_64
            dest=/opt/mysql 
            state=link
            owner=mysql
            group=mysql
      tags: "deploy"

    - name: Initialize mysql database
      command: scripts/mysql_install_db --user=mysql
               chdir=/opt/mysql-5.6.20-linux-glibc2.5-x86_64
               creates=/opt//opt/mysql-5.6.20-linux-glibc2.5-x86_64/data/mysql
      tags: "deploy"

    - name: Install Startup Script
      template: src=/home/yan/software/mysql.server.j2 
                dest=/etc/init.d/mysql

    - name: Set Executeable Startup Script
      file: path=/etc/init.d/mysql
            owner=root
            group=root
            mode=0755

    - name: Start MySQL Service
      service: name=mysql state=started
            
    - name: Wait mysql startup
      wait_for: port=3306

    - name: Copy secure.sql
      copy: src=/home/yan/software/secure.sql
            dest=/home/yan 
            
    - name: Secureing mysql
      shell: bin/mysql -S /tmp/mysql.sock </home/yan/secure.sql
             chdir=/opt/mysql
            
